web:
  container_name: php7_apache_oci8
  build: .
  ports:
    - "80:80"
  volumes:
    - ./src:/var/www/html/
    - ./conf/apache:/etc/apache2/sites-enabled/
    - ./conf/php:/usr/local/etc/php/
  links:
    - oracle

oracle:
  image: sath89/oracle-xe-11g
  container_name: oracle-php
  ports:
    - "1521:1521"
  volumes:
    - /home/fahim/oracle_data:/u01/app/oracle
